### ISSUE TITLE
Question about update Az Module related to #5

### ISSUE THREAD

**Issue by hannwang1** [microsoft/AzureAutomation-Account-Modules-Update#15]
I have an automation account I am going to only use Az module.  From Azure doc https://docs.microsoft.com/en-us/azure/automation/az-modules, AzureRM modules are still installed when create automation account and there is no way to remove the AzureRM modules.  The doc says "When a new Automation Account is created the existing AzureRM modules will still be installed and the tutorial runbooks will still be authored with AzureRM cmdlets."  This means both AzureRM and Az modules are installed for my automation account.  The ReadMe of this "Update-AutomationAzureModulesForAccount" says "Avoid starting this runbook on Automation accounts that contain both AzureRM and Az modules."   

I am confused.  My question is, can this runbook be used to update Az Modules on the automation account?  Because every automation account will have AzureRM modules installed by default.  I haven't found an option to remove AzureRM modules (the delete button is not available).  
Thanks for your help in advance.

**Comment by AnatoliB** [comment]
This advice is outdated, it should be removed:

> Avoid starting this runbook on Automation accounts that contain both AzureRM and Az modules

Thank you for noticing this. Older versions of this runbook were not designed to handle Az modules well, so this advice was relevant. The latest version does not have this restriction, you just need to pass a correct value to the `AzureModuleClass` parameter.

**Comment by AnatoliB** [comment]
README is fixed.
