### ISSUE TITLE
Unable to import module in Automation account

### ISSUE THREAD

**Issue by githubvick** [microsoft/AzureAutomation-Account-Modules-Update#16]
After I add the module inside the Azure automation account, it says importing for a few minutes and fails with this error.

Error importing the module AzureAutomation-Account-Modules-Update-master. Import failed with the following error: Orchestrator.Shared.AsyncModuleImport.ModuleImportException: Cannot import the module of name AzureAutomation-Account-Modules-Update-master, as the module structure was invalid.

Please check.

**Comment by AnatoliB** [comment]
I'm assuming you are trying to import the content of this repository into Azure Automation as a PowerShell module. This is not intended to work, as this code has never been packaged as a _module_. This should be technically possible, but not without making changes to the source code.

The primary way to use this code is to import the **Update-AutomationAzureModulesForAccount.ps1** file into your Automation account as a _PowerShell runbook_, and then invoke it like any other runbook.

You can also invoke it as a stand-alone script that can be executed from any machine outside of Azure Automation.
