### ISSUE TITLE
Unable to import VirtualDesktop into Automation Account via the portal

### ISSUE THREAD

**Issue by Rossco8** [microsoft/AzureAutomation-Account-Modules-Update#23]
I have created a new Automation Account (via the Portal) and have select Modules -> Browse Gallery and searched for VirtualDesktop

I selected Virtual Desktop module version 1.1.0 and clicked Import

After a minute of importing, the following error appears. Any suggestions for what I can do? I'm sure this worked a few weeks ago:

> Error importing the module VirtualDesktop. Import failed with the following error: Orchestrator.Shared.AsyncModuleImport.ModuleImportException: An error occurred during module validation. When importing the module to an internal PowerShell session, it was not able to be loaded by PowerShell. There is likely an issue with the contents of the module that results in PowerShell's not being able to load it. Please verify that the module imports successfully in a local PowerShell session, correct any issues, and then try importing again.
>

**Comment by AnatoliB** [comment]
I would suggest opening a support request for the Azure Automation service, and someone will be able to help you.
